name: eeg-cursor-bci
dependencies:
  - python=3.8
  - pip
  - pip:
    - h5pickle==0.4.2
    – h5py==2.10.0
    - matplotlib==3.3.2
    - numpy==1.20.1
    – scipy==1.6.2
    - tensorboard==2.6.0
    – torch==1.7.0
    – tqdm==4.56.0